[build]
  command = "python portfolio_daniel_dev/manage.py collectstatic --noinput"
  publish = "portfolio_daniel_developer/portfolio_daniel_developer"
  functions = "functions"
  environment = { DJANGO_SETTINGS_MODULE = "portfolio_daniel_dev.settings" }

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "portfolio_daniel_dev.settings"
  SECRET_KEY = "django-insecure-@z2)p&x4lub&4dv-+p(3f@0%o(p+-=t(2))s61o10)25icodl^"
  DEBUG = "False"

[context.deploy-preview.environment]
  DJANGO_SETTINGS_MODULE = "portfolio_daniel_dev.settings"
  SECRET_KEY = "your-secret-key-for-deploy-preview"
  DEBUG = "True"

[context.split1]
  command = "python manage.py migrate"

[context.split2]
  command = "gunicorn portfolio_daniel_dev.wsgi:application"
