# Generated by Django 5.0.1 on 2024-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
            ],
        ),
    ]
